import { generateSceneImageGemini, generateScriptGemini } from "./gemini";
import {
	generateSceneImageOpenRouter,
	generateScriptOpenRouter,
} from "./openrouter";
import { generateVoiceoverGemini, type VoiceoverResult } from "./tts";
import type { AiBrief, AiImageResult, AiScene, AiScriptResult } from "./types";

export type AiProviderId = "openrouter" | "gemini";

export interface AiConfig {
	provider: AiProviderId;
	apiKey: string;
	textModel: string;
	imageModel: string;
	ttsModel: string;
	voice: string;
}

export interface AiProviderInfo {
	id: AiProviderId;
	label: string;
	keyPlaceholder: string;
	keyHelp: string;
	/** Free text models worth offering for this provider. */
	freeTextModels: string[];
	textModelHint: string;
	imageModelHint: string;
	ttsModelHint: string;
	imageNote: string;
	ttsNote: string;
}

export const AI_PROVIDERS: AiProviderInfo[] = [
	{
		id: "openrouter",
		label: "OpenRouter",
		keyPlaceholder: "sk-or-v1-...",
		keyHelp: "One key for many models. Free models (id ends in :free) cost nothing.",
		freeTextModels: [
			"nvidia/nemotron-3-super-120b-a12b:free",
			"google/gemma-4-26b-a4b-it:free",
			"thinkingmachines/inkling:free",
			"inclusionai/ling-3.0-flash-sante:free",
		],
		textModelHint: "nvidia/nemotron-3-super-120b-a12b:free",
		imageModelHint: "google/gemini-2.5-flash-image",
		ttsModelHint: "",
		imageNote:
			"OpenRouter has no free image models, so scene frames need a little credit on the account.",
		ttsNote: "Voiceover is only available on Google Gemini.",
	},
	{
		id: "gemini",
		label: "Google Gemini",
		keyPlaceholder: "AQ....",
		keyHelp:
			"Google AI Studio key (starts with AQ.). Free for scripts; image frames need billing enabled.",
		freeTextModels: [],
		textModelHint: "gemini-3.8-flash",
		imageModelHint: "gemini-3.1-flash-lite-image",
		ttsModelHint: "gemini-2.5-flash-preview-tts",
		imageNote:
			"Google's free tier does not include image generation (its quota is 0), so scene frames need billing enabled on the Google Cloud project. Scripts are free.",
		ttsNote:
			"Voiceover is generated by Google TTS and lands on the timeline as real audio. It needs billing enabled.",
	},
];

export function providerInfo(id: AiProviderId): AiProviderInfo {
	return AI_PROVIDERS.find((p) => p.id === id) ?? AI_PROVIDERS[0];
}

export async function generateScript({
	brief,
	config,
}: {
	brief: AiBrief;
	config: AiConfig;
}): Promise<AiScriptResult> {
	if (config.provider === "gemini") {
		return generateScriptGemini({
			brief,
			apiKey: config.apiKey,
			textModel: config.textModel,
		});
	}
	return generateScriptOpenRouter({
		brief,
		apiKey: config.apiKey,
		textModel: config.textModel,
	});
}

export async function generateSceneImage({
	scene,
	brief,
	config,
}: {
	scene: AiScene;
	brief: AiBrief;
	config: AiConfig;
}): Promise<AiImageResult> {
	if (config.provider === "gemini") {
		return generateSceneImageGemini({
			scene,
			brief,
			apiKey: config.apiKey,
			imageModel: config.imageModel,
		});
	}
	return generateSceneImageOpenRouter({
		scene,
		brief,
		apiKey: config.apiKey,
		imageModel: config.imageModel,
	});
}

/**
 * Real spoken voiceover. Only Google exposes a speech model here, and there is no
 * synthetic fallback: a failure returns no audio plus the reason.
 */
export async function generateVoiceover({
	text,
	config,
}: {
	text: string;
	config: AiConfig;
}): Promise<VoiceoverResult> {
	if (config.provider !== "gemini") {
		return {
			blob: null,
			warning: "Voiceover is only available with the Google Gemini provider.",
		};
	}
	return generateVoiceoverGemini({
		text,
		apiKey: config.apiKey,
		ttsModel: config.ttsModel,
		voice: config.voice,
	});
}
